### ISSUE TITLE
Related CMake issue

### ISSUE THREAD

**Issue by technic** [jcar87/cmake-macos-runtime-dependencies#1]
Hi, I am facing a problem that when getting libraries from conan the GET_RUNTIME_DEPENDENCIES cmake command fails to find them.
Somehow googling ended up in this repository. Is there a related CMake issue for this? Is there a workaround?

Regards
Alex

**Comment by jcar87** [comment]
Hi @technic - mm I think it would depend on which operating system you're on (macOS, Linux, Windows) and which version of Conan as well. Which platform is this failing on for you?

**Comment by technic** [comment]
macOS

**Comment by technic** [comment]
Ok I found it, this is the CMake issue: https://gitlab.kitware.com/cmake/cmake/-/issues/24400
